#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 20 00:14:25 2018

@author: allenwilliams
"""

import numpy

def modInverse(m, a):
    m_init,p2,p1,p0,q2,q1,i = a,0,1,0,0,0,0
    
    if (m == 1): return 0
    while (a > 1):
        q = a // m
        t = m
        m = a % m    #<-- a=qt+m
        
        a = t
        if (i > 1):
            p0 = (p2-p1*q2) % m_init
            p2 = p1
            p1 = p0
        q2 = q1
        q1 = q
        i+=1
    p0 = (p2-p1*q2) % m_init
    return p0
